# -*- coding: utf-8 -*-
"""app_raiz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dXExhEfaWz8sgczmocUemFtRjN9D41Tz
"""

import streamlit as st
import datetime
import os

# --- Configuración inicial ---
st.set_page_config(page_title="Panel KSTM - Viento y Olas", layout="wide")

st.title("🌊 Panel de Pronóstico Marítimo (KSTM)")
st.markdown("""
Visualización combinada de **altura significativa de ola** (Copernicus) y **viento máximo pronosticado** (GFS)
en los principales puertos del Atlántico Sur.
""")

# --- Directorio donde están los mapas HTML ---
RUTA_MAPAS = "./mapas_html"  # o tu subcarpeta del repo

# --- Buscar archivos disponibles ---
if not os.path.exists(RUTA_MAPAS):
    st.error("❌ No se encontró la carpeta con los mapas HTML.")
    st.stop()

archivos = sorted(
    [f for f in os.listdir(RUTA_MAPAS) if f.endswith(".html")]
)

if not archivos:
    st.warning("No hay mapas HTML disponibles.")
    st.stop()

# --- Crear menú desplegable con fechas ---
# Los nombres de archivos deben tener formato: mapa_YYYYMMDD.html
opciones = []
for f in archivos:
    try:
        fecha_str = f.replace("mapa_", "").replace(".html", "")
        fecha_dt = datetime.datetime.strptime(fecha_str, "%Y%m%d")
        opciones.append((f, fecha_dt.strftime("%d %b %Y")))
    except:
        pass

if not opciones:
    st.error("No se pudo interpretar ninguna fecha de los archivos.")
    st.stop()

# --- Menú de selección ---
archivos_ordenados = sorted(opciones, key=lambda x: x[0])
labels = [f"Pronóstico para {x[1]}" for x in archivos_ordenados]
seleccion = st.selectbox("Seleccioná el día a visualizar:", labels, index=0)

# --- Mostrar el HTML correspondiente ---
archivo_seleccionado = archivos_ordenados[labels.index(seleccion)][0]
ruta_html = os.path.join(RUTA_MAPAS, archivo_seleccionado)

st.subheader(f"🗓️ {seleccion}")

# Mostrar el HTML embebido dentro del panel
with open(ruta_html, "r", encoding="utf-8") as f:
    html = f.read()

st.components.v1.html(html, height=700, scrolling=True)

st.markdown("---")
st.caption("Desarrollado por KSTM — Datos GFS & Copernicus")